### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ernspa94** [aws/amazon-ec2-spot-interrupter#58]
When i try to install the ec2-spot-interrupter i receive this error:

Error: ec2-spot-interrupter: SHA256 mismatch
Expected: b0cda18f79aace89424c8963a6d39107c9168535a9b8bd0424fb2bb57d82b531
Actual: e8a946b2b20504e3aa666bd91ae2b60c68c328712e848cb1d6520866a5865070

I tried in different linux distros and always the same.
How can i solve it?

**Comment by bwagner5** [comment]
apologies, should be fixed now. You may have to clear your brew cache.
